#!/usr/bin/env python3
"""
Evolution-Guided Recovery for the Bolt Supervisor

When the Transport supervisor detects a persistent stuck state (same failure
for N consecutive cycles), this script:

  1. Maps the stuck state to the most-likely-failing CULink-EFA dimension
  2. Loads the design space YAML and enumerates alternatives for that dimension
  3. Filters out alternatives that violate constraints
  4. For each valid alternative, generates a recovery candidate by splicing
     a code template into the seed kernel
  5. Runs cascaded evaluation (L0 parse + L1 compile at minimum)
  6. Ranks candidates and outputs a JSON report

Can be triggered manually or auto-triggered by bolt-supervisor-v2.sh.

Usage:
    # Manual: investigate C0_NO_WORKER stuck state
    python3 evolution-recovery.py --state C0_NO_WORKER --stuck-cycles 5 \\
        --seed-kernel /path/to/transport_worker.cpp

    # Dry-run: show what would happen without evolving
    python3 evolution-recovery.py --state DISPATCHING --stuck-cycles 3 --dry-run

    # Demo mode: simulated run with mock data
    python3 evolution-recovery.py --demo
"""

from __future__ import annotations

import argparse
import hashlib
import json
import logging
import os
import re
import shutil
import sys
import tempfile
import time
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Any, Optional

import yaml

logger = logging.getLogger("evolution-recovery")

# =============================================================================
# Constants
# =============================================================================

SCRIPT_DIR = Path(__file__).resolve().parent
CUCO_DIR = SCRIPT_DIR.parent / "cuco-codesign"

DEFAULT_CONFIG_PATH = SCRIPT_DIR / "evolution-recovery-config.yaml"
DEFAULT_DESIGN_SPACE = CUCO_DIR / "design-space" / "culink-efa.yaml"
DEFAULT_TEMPLATES_DIR = SCRIPT_DIR / "recovery-templates"

# State-to-dimension mapping: which CULink dimension is most likely
# responsible for each supervisor-detected failure state.
STATE_TO_DIMENSION: dict[str, tuple[Optional[str], str]] = {
    "C0_NO_WORKER": (
        "sync",
        "GPU signal not reaching CPU worker -- try different sync mechanism",
    ),
    "C0_TIMEOUT": (
        "issuer",
        "GPU coordinator not generating descriptors -- try different issuer strategy",
    ),
    "DISPATCHING": (
        "backend",
        "fi_writemsg posting but data not arriving -- try different backend",
    ),
    "DISPATCHING_TIMEOUT": (
        "backend",
        "Transfer started but timing out -- backend or granularity issue",
    ),
    "NO_WORKERS": (
        None,
        "Infrastructure issue -- not a kernel design problem",
    ),
    "NO_BOLT": (
        None,
        "Bolt not loaded -- rebuild with USE_BOLT=1",
    ),
    "PEERS_MISSING": (
        None,
        "Infrastructure issue -- not a kernel design problem",
    ),
    "BARRIER_WAIT": (
        None,
        "Waiting for barrier -- may resolve on its own",
    ),
    "ALL_PASS": (
        None,
        "Everything working -- no recovery needed",
    ),
    "NO_PODS": (
        None,
        "No pods running -- infrastructure issue",
    ),
    "UNKNOWN": (
        None,
        "Unknown state -- cannot map to dimension",
    ),
}

# Short dimension symbol mapping (for --current-config parsing)
DIM_SYMBOL_MAP = {
    "B": "backend",
    "P": "placement",
    "S": "sync",
    "I": "issuer",
    "G": "granularity",
}


# =============================================================================
# Data Structures
# =============================================================================

@dataclass
class RecoveryCandidate:
    """A recovery candidate generated by template splicing."""
    id: str
    dimension: str
    original_value: str
    alternative_value: str
    template_path: Optional[str]
    candidate_path: Optional[str]
    eval_level: str = "pending"
    eval_passed: bool = False
    eval_score: float = 0.0
    eval_errors: Optional[str] = None
    eval_diagnostics: Optional[str] = None

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class RecoveryConfig:
    """Parsed recovery configuration."""
    min_stuck_cycles: int = 3
    max_candidates_per_run: int = 6
    eval_levels: list[str] = field(default_factory=lambda: ["L0", "L1"])
    full_eval_threshold: int = 5
    auto_deploy: bool = False
    cooldown_cycles: int = 10
    current_config: dict[str, str] = field(default_factory=dict)
    tried_alternatives: list[str] = field(default_factory=list)
    design_space_yaml: str = ""
    templates_dir: str = ""
    workspace: str = ""
    reports_dir: str = ""


# =============================================================================
# Design Space Loader
# =============================================================================

class DesignSpace:
    """Loads and queries the CULink-EFA design space YAML."""

    def __init__(self, yaml_path: str):
        self.yaml_path = yaml_path
        with open(yaml_path) as f:
            self.raw = yaml.safe_load(f)

        self.dimensions = {}
        for dim_name in ["backend", "placement", "sync", "issuer", "granularity"]:
            if dim_name in self.raw:
                self.dimensions[dim_name] = self.raw[dim_name]

        self.constraints = self.raw.get("constraints", [])

    def get_values(self, dimension: str) -> list[str]:
        """Return all possible values for a dimension."""
        dim = self.dimensions.get(dimension, {})
        return list(dim.get("values", {}).keys())

    def get_default(self, dimension: str) -> str:
        """Return the default value for a dimension."""
        dim = self.dimensions.get(dimension, {})
        return dim.get("default", "")

    def get_value_info(self, dimension: str, value: str) -> dict:
        """Return metadata for a specific dimension value."""
        dim = self.dimensions.get(dimension, {})
        return dim.get("values", {}).get(value, {})

    def get_alternatives(self, dimension: str, current_value: str) -> list[str]:
        """Return all values for a dimension except the current one."""
        all_values = self.get_values(dimension)
        return [v for v in all_values if v != current_value]

    def check_constraints(
        self, config: dict[str, str], target_dim: str, new_value: str
    ) -> list[str]:
        """
        Check if setting target_dim=new_value violates any hard constraints.
        Returns a list of violated constraint names (empty = OK).
        """
        test_config = dict(config)
        test_config[target_dim] = new_value

        violations = []
        for constraint in self.constraints:
            if constraint.get("severity") != "hard":
                continue
            rule = constraint.get("rule", "")
            name = constraint.get("name", "unnamed")
            if self._rule_violated(rule, test_config):
                violations.append(name)

        return violations

    def _rule_violated(self, rule: str, config: dict[str, str]) -> bool:
        """
        Simple rule evaluator for constraint checking.
        Handles patterns like:
          "B=gdrcopy_mmio OR S=gdrcopy_mmio => gdrdrv kernel module loaded"
          "G=bulk_all => P must be sequential"
          "I=cpu_worker => S != d2h_ring"
          "B=staging_copy_bulk AND G in {per_token, adaptive_chunk} => INVALID"
        """
        B = config.get("backend", "")
        P = config.get("placement", "")
        S = config.get("sync", "")
        I = config.get("issuer", "")
        G = config.get("granularity", "")

        # bulk_all_requires_sequential
        if "G=bulk_all" in rule and "P must be sequential" in rule:
            if G == "bulk_all" and P != "sequential":
                return True

        # cpu_worker_no_d2h_ring
        if "I=cpu_worker" in rule and "S != d2h_ring" in rule:
            if I == "cpu_worker" and S == "d2h_ring":
                return True

        # fully_overlapped_needs_fine_sync
        if "P=fully_overlapped" in rule and "S in {" in rule:
            if P == "fully_overlapped":
                allowed = {"host_pinned_volatile", "d2h_ring", "gdrcopy_mmio"}
                if S not in allowed:
                    return True

        # staging_copy_conflicts_with_fine_granularity
        if "B=staging_copy_bulk" in rule and "G in {per_token, adaptive_chunk}" in rule:
            if B == "staging_copy_bulk" and G in ("per_token", "adaptive_chunk"):
                return True

        # fi_write_requires_dmabuf — soft check (we note it but don't block)
        # We only block hard structural incompatibilities above.

        return False


# =============================================================================
# Template Splicer
# =============================================================================

class TemplateSplicer:
    """Generates recovery candidates by splicing templates into a seed kernel."""

    def __init__(self, templates_dir: str, workspace: str):
        self.templates_dir = Path(templates_dir)
        self.workspace = Path(workspace)
        self.workspace.mkdir(parents=True, exist_ok=True)

    def available_templates(self, dimension: str) -> dict[str, Path]:
        """Return {value_name: template_path} for a dimension."""
        result = {}
        pattern = f"{dimension}_*.cpp.tmpl"
        for tmpl_path in sorted(self.templates_dir.glob(pattern)):
            # Extract value name: backend_fi_write.cpp.tmpl -> fi_write
            stem = tmpl_path.stem.replace(".cpp", "")  # backend_fi_write
            value_name = stem.replace(f"{dimension}_", "", 1)  # fi_write
            result[value_name] = tmpl_path
        return result

    def _match_template(
        self, templates: dict[str, Path], alternative_value: str
    ) -> Optional[Path]:
        """
        Find the best matching template for an alternative value.

        Matching strategy (in order):
          1. Exact match: template name == alternative value
          2. Prefix match: alternative starts with template name
          3. Reverse prefix: template name starts with alternative
          4. Normalized match: strip common prefixes (d2h_ring_, host_pinned_)
             and compare
          5. Substring match: template name is contained in alternative or
             vice versa
        """
        # 1. Exact match
        if alternative_value in templates:
            return templates[alternative_value]

        # 2-5. Fuzzy matching
        strip_prefixes = ["d2h_ring_", "host_pinned_", "staging_copy_"]
        def normalize(s: str) -> str:
            result = s
            for pfx in strip_prefixes:
                result = result.replace(pfx, "")
            return result

        alt_norm = normalize(alternative_value)

        for tmpl_name, tmpl_path in templates.items():
            # 2. Prefix match
            if alternative_value.startswith(tmpl_name):
                return tmpl_path
            # 3. Reverse prefix
            if tmpl_name.startswith(alternative_value):
                return tmpl_path
            # 4. Normalized match
            tmpl_norm = normalize(tmpl_name)
            if alt_norm == tmpl_norm:
                return tmpl_path
            # 5. Substring match
            if tmpl_norm in alt_norm or alt_norm in tmpl_norm:
                return tmpl_path

        return None

    def splice(
        self,
        seed_path: str,
        dimension: str,
        alternative_value: str,
        candidate_id: str,
    ) -> Optional[str]:
        """
        Create a recovery candidate by splicing a template into the seed.

        Returns the path to the generated candidate file, or None if no
        template is available.
        """
        templates = self.available_templates(dimension)

        template_path = self._match_template(templates, alternative_value)

        if template_path is None:
            logger.warning(
                f"No template found for {dimension}={alternative_value} "
                f"(available: {list(templates.keys())})"
            )
            return None

        # Read seed and template
        seed_content = Path(seed_path).read_text()
        template_content = template_path.read_text()

        # Strategy: append the template as a clearly-marked alternative
        # section at the end of the seed file, wrapped in #ifdef guards.
        # This ensures the file is syntactically valid C++ for L0/L1 eval.
        guard_name = f"RECOVERY_{dimension.upper()}_{alternative_value.upper()}"
        guard_name = re.sub(r"[^A-Z0-9_]", "_", guard_name)

        spliced = seed_content + f"""

// =============================================================================
// RECOVERY CANDIDATE: {dimension}={alternative_value}
// Generated by evolution-recovery.py
// Template: {template_path.name}
// =============================================================================
#ifdef {guard_name}
{template_content}
#endif // {guard_name}
"""

        # Write candidate
        candidate_dir = self.workspace / candidate_id
        candidate_dir.mkdir(parents=True, exist_ok=True)
        candidate_path = candidate_dir / f"bolt_worker_{alternative_value}.cpp"
        candidate_path.write_text(spliced)

        return str(candidate_path)


# =============================================================================
# L0 Parse Evaluator (standalone, no CUCo dependency)
# =============================================================================

class L0Evaluator:
    """
    Minimal L0 parse check that does not depend on the CUCo evaluation module.
    Checks structural validity of C++ source files.
    """

    @staticmethod
    def evaluate(candidate_path: str) -> tuple[bool, str]:
        """
        Run L0 parse check on a candidate file.
        Returns (passed, diagnostics).
        """
        path = Path(candidate_path)
        if not path.exists():
            return False, f"File not found: {candidate_path}"

        content = path.read_text()
        errors = []

        # Check for balanced braces
        brace_depth = 0
        for i, ch in enumerate(content):
            if ch == '{':
                brace_depth += 1
            elif ch == '}':
                brace_depth -= 1
                if brace_depth < 0:
                    errors.append(f"Unmatched closing brace at char {i}")
                    break
        if brace_depth > 0:
            errors.append(f"Unmatched opening braces: {brace_depth} unclosed")

        # Check for #include
        if "#include" not in content:
            errors.append("No #include directives found")

        # Check template markers are balanced
        starts = content.count("TEMPLATE-MARKER:")
        ends = content.count("TEMPLATE-MARKER-END:")
        if starts > 0 and starts != ends:
            errors.append(f"Unbalanced template markers: {starts} starts, {ends} ends")

        if errors:
            return False, "; ".join(errors)
        return True, "L0 parse OK"


# =============================================================================
# Recovery Orchestrator
# =============================================================================

class RecoveryOrchestrator:
    """
    Main orchestrator that ties together state mapping, design space querying,
    template splicing, and cascaded evaluation.
    """

    def __init__(
        self,
        config_path: Optional[str] = None,
        design_space_path: Optional[str] = None,
        templates_dir: Optional[str] = None,
    ):
        # Load configuration
        self.config = self._load_config(config_path or str(DEFAULT_CONFIG_PATH))

        # Override paths if provided
        ds_path = design_space_path or self.config.design_space_yaml or str(DEFAULT_DESIGN_SPACE)
        tmpl_dir = templates_dir or self.config.templates_dir or str(DEFAULT_TEMPLATES_DIR)
        workspace = self.config.workspace or str(SCRIPT_DIR / "recovery-workspace")
        self.reports_dir = Path(
            self.config.reports_dir or str(SCRIPT_DIR / "recovery-reports")
        )
        self.reports_dir.mkdir(parents=True, exist_ok=True)

        # Initialize components
        self.design_space = DesignSpace(ds_path)
        self.splicer = TemplateSplicer(tmpl_dir, workspace)
        self.evaluator = L0Evaluator()

    def _load_config(self, path: str) -> RecoveryConfig:
        """Load configuration from YAML."""
        p = Path(path)
        if not p.exists():
            logger.warning(f"Config not found at {path}, using defaults")
            return RecoveryConfig()

        with open(p) as f:
            raw = yaml.safe_load(f)

        recovery = raw.get("recovery", {})
        return RecoveryConfig(
            min_stuck_cycles=recovery.get("min_stuck_cycles", 3),
            max_candidates_per_run=recovery.get("max_candidates_per_run", 6),
            eval_levels=recovery.get("eval_levels", ["L0", "L1"]),
            full_eval_threshold=recovery.get("full_eval_threshold", 5),
            auto_deploy=recovery.get("auto_deploy", False),
            cooldown_cycles=recovery.get("cooldown_cycles", 10),
            current_config=recovery.get("current_config", {}),
            tried_alternatives=recovery.get("tried_alternatives", []),
            design_space_yaml=recovery.get("design_space_yaml", ""),
            templates_dir=recovery.get("templates_dir", ""),
            workspace=recovery.get("workspace", ""),
            reports_dir=recovery.get("reports_dir", ""),
        )

    def run(
        self,
        state: str,
        stuck_cycles: int,
        current_config: Optional[dict[str, str]] = None,
        seed_kernel: Optional[str] = None,
        dry_run: bool = False,
    ) -> dict[str, Any]:
        """
        Run evolution-guided recovery.

        Args:
            state: Supervisor state (e.g., C0_NO_WORKER, DISPATCHING)
            stuck_cycles: Number of consecutive cycles in this state
            current_config: Current CULink config (overrides config file)
            seed_kernel: Path to the seed kernel file
            dry_run: If True, just show what would happen

        Returns:
            JSON-serializable report dict
        """
        timestamp = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
        run_id = f"recovery_{state}_{int(time.time())}"

        # Step 1: Map state to dimension
        dimension, reason = STATE_TO_DIMENSION.get(state, (None, f"Unknown state: {state}"))

        report: dict[str, Any] = {
            "run_id": run_id,
            "timestamp": timestamp,
            "state": state,
            "stuck_cycles": stuck_cycles,
            "dimension_targeted": dimension,
            "reason": reason,
            "candidates_tried": 0,
            "candidates": [],
            "best_candidate": None,
            "recommendation": "",
            "dry_run": dry_run,
        }

        if dimension is None:
            report["recommendation"] = f"No kernel recovery possible: {reason}"
            logger.info(f"State {state}: {reason}")
            self._save_report(report)
            return report

        # Step 2: Check stuck cycle threshold
        if stuck_cycles < self.config.min_stuck_cycles:
            report["recommendation"] = (
                f"Stuck for {stuck_cycles} cycles, threshold is "
                f"{self.config.min_stuck_cycles}. Waiting."
            )
            logger.info(report["recommendation"])
            self._save_report(report)
            return report

        # Step 3: Get current config
        config = current_config or self.config.current_config
        if not config:
            config = {
                "backend": "d2h_ring_fi_send",
                "placement": "split_put_wait",
                "sync": "d2h_ring",
                "issuer": "multi_warp",
                "granularity": "per_expert_batch",
            }
        report["current_config"] = config
        current_value = config.get(dimension, "")

        # Step 4: Enumerate alternatives
        alternatives = self.design_space.get_alternatives(dimension, current_value)
        logger.info(
            f"Dimension '{dimension}': current='{current_value}', "
            f"alternatives={alternatives}"
        )

        # Step 5: Filter by constraints
        valid_alternatives = []
        for alt in alternatives:
            violations = self.design_space.check_constraints(config, dimension, alt)
            if violations:
                logger.info(f"  {alt}: SKIPPED (violates {violations})")
            else:
                # Also skip already-tried alternatives
                tried_key = f"{dimension}={alt}"
                if tried_key in self.config.tried_alternatives:
                    logger.info(f"  {alt}: SKIPPED (already tried)")
                else:
                    valid_alternatives.append(alt)
                    logger.info(f"  {alt}: VALID")

        # Limit candidates
        valid_alternatives = valid_alternatives[: self.config.max_candidates_per_run]
        report["valid_alternatives"] = valid_alternatives

        if not valid_alternatives:
            report["recommendation"] = (
                f"No valid alternatives for {dimension} (current={current_value}). "
                f"All alternatives either violate constraints or were already tried."
            )
            self._save_report(report)
            return report

        if dry_run:
            report["recommendation"] = (
                f"DRY RUN: Would try {len(valid_alternatives)} alternatives for "
                f"{dimension}: {valid_alternatives}"
            )
            for alt in valid_alternatives:
                info = self.design_space.get_value_info(dimension, alt)
                desc = info.get("description", "No description")
                if isinstance(desc, str):
                    desc = desc.strip()[:120]
                report["candidates"].append({
                    "alternative": alt,
                    "description": desc,
                    "status": "would_try",
                })
            report["candidates_tried"] = 0
            self._save_report(report)
            return report

        # Step 6: Generate and evaluate candidates
        if seed_kernel is None:
            # Default seed: transport_worker.cpp
            seed_kernel = str(
                Path("<HOME>/<project>"
                     "DeepEP/csrc/bolt/transport_worker.cpp")
            )
            if not Path(seed_kernel).exists():
                # Fallback to baseline header
                seed_kernel = str(
                    CUCO_DIR / "kernels" / "baseline" / "internode_header.cu"
                )

        if not Path(seed_kernel).exists():
            report["recommendation"] = f"Seed kernel not found: {seed_kernel}"
            self._save_report(report)
            return report

        candidates: list[RecoveryCandidate] = []
        for alt in valid_alternatives:
            cid = f"{run_id}_{dimension}_{alt}"
            candidate = RecoveryCandidate(
                id=cid,
                dimension=dimension,
                original_value=current_value,
                alternative_value=alt,
                template_path=None,
                candidate_path=None,
            )

            # Splice template
            candidate_path = self.splicer.splice(
                seed_kernel, dimension, alt, cid
            )
            if candidate_path is None:
                candidate.eval_level = "no_template"
                candidate.eval_diagnostics = (
                    f"No template available for {dimension}={alt}"
                )
                candidates.append(candidate)
                continue

            candidate.candidate_path = candidate_path
            candidate.template_path = str(
                self.splicer.available_templates(dimension).get(alt, "")
            )

            # L0 evaluation
            passed, diag = self.evaluator.evaluate(candidate_path)
            candidate.eval_level = "L0_parse"
            candidate.eval_passed = passed
            candidate.eval_diagnostics = diag

            if passed:
                candidate.eval_score = 0.1  # Passed L0
                # Try L1 if configured
                if "L1" in self.config.eval_levels:
                    l1_passed, l1_diag = self._try_l1_compile(candidate_path)
                    if l1_passed:
                        candidate.eval_level = "L1_compile"
                        candidate.eval_score = 0.5
                        candidate.eval_diagnostics = l1_diag
                    else:
                        candidate.eval_level = "L1_compile_failed"
                        candidate.eval_score = 0.1
                        candidate.eval_errors = l1_diag
            else:
                candidate.eval_score = 0.0
                candidate.eval_errors = diag

            candidates.append(candidate)
            logger.info(
                f"  Candidate {alt}: {candidate.eval_level} "
                f"passed={candidate.eval_passed} score={candidate.eval_score}"
            )

        # Step 7: Rank candidates
        candidates.sort(key=lambda c: c.eval_score, reverse=True)
        report["candidates"] = [c.to_dict() for c in candidates]
        report["candidates_tried"] = len(candidates)

        # Step 8: Select best
        best = candidates[0] if candidates and candidates[0].eval_score > 0 else None
        if best:
            report["best_candidate"] = best.to_dict()
            report["recommendation"] = (
                f"Best recovery candidate: {dimension}={best.alternative_value} "
                f"(eval_level={best.eval_level}, score={best.eval_score}). "
            )
            if self.config.auto_deploy and best.eval_score >= 0.5:
                report["recommendation"] += "AUTO-DEPLOY: enabled, deploying candidate."
            elif best.eval_score >= 0.5:
                report["recommendation"] += (
                    "Candidate passed L1 compile. Set auto_deploy=true in config "
                    "to enable automatic deployment, or deploy manually."
                )
            else:
                report["recommendation"] += (
                    "Candidate only passed L0. Manual review recommended before deployment."
                )
        else:
            report["recommendation"] = (
                f"No viable candidates found for {dimension} recovery. "
                f"All alternatives failed evaluation."
            )

        self._save_report(report)
        return report

    def _try_l1_compile(self, candidate_path: str) -> tuple[bool, str]:
        """
        Attempt L1 compile check. This is a lightweight check that verifies
        the file can be parsed by a C++ compiler (syntax check only).
        Falls back gracefully if nvcc/g++ is not available.
        """
        import subprocess

        # Try g++ syntax check first (faster, more available)
        for compiler in ["g++", "nvcc"]:
            try:
                if compiler == "g++":
                    cmd = [
                        "g++", "-fsyntax-only", "-std=c++17",
                        "-x", "c++",
                        "-I/opt/amazon/efa/include",
                        candidate_path,
                    ]
                else:
                    cmd = [
                        "nvcc", "-c", "--dry-run",
                        "-arch=sm_90a",
                        "-I/opt/amazon/efa/include",
                        candidate_path,
                    ]

                proc = subprocess.run(
                    cmd,
                    capture_output=True,
                    text=True,
                    timeout=30,
                )
                if proc.returncode == 0:
                    return True, f"L1 compile OK ({compiler})"
                else:
                    # Extract first few error lines
                    err_lines = [
                        line for line in proc.stderr.splitlines()
                        if "error" in line.lower()
                    ][:5]
                    return False, f"L1 compile failed ({compiler}): " + "; ".join(err_lines)

            except FileNotFoundError:
                continue
            except subprocess.TimeoutExpired:
                return False, f"L1 compile timed out ({compiler})"
            except Exception as e:
                continue

        return False, "No compiler available (tried g++, nvcc)"

    def _save_report(self, report: dict):
        """Save the recovery report to disk."""
        report_path = self.reports_dir / f"{report['run_id']}.json"
        with open(report_path, "w") as f:
            json.dump(report, f, indent=2, default=str)
        logger.info(f"Report saved: {report_path}")

    def run_demo(self) -> dict[str, Any]:
        """
        Demo mode: simulate a C0_NO_WORKER stuck state with mock data.
        Uses the baseline kernel header as the seed.
        """
        logger.info("=" * 60)
        logger.info("DEMO MODE: Evolution-guided recovery")
        logger.info("=" * 60)

        # Use transport_worker.cpp as seed (preferred; it has balanced braces)
        seed_candidates = [
            Path("<HOME>/<project>"
                 "DeepEP/csrc/bolt/transport_worker.cpp"),
            CUCO_DIR / "kernels" / "baseline" / "internode_header.cu",
        ]
        seed_kernel = None
        for sp in seed_candidates:
            if sp.exists():
                seed_kernel = str(sp)
                break

        if seed_kernel is None:
            logger.error("No seed kernel found for demo")
            return {"error": "No seed kernel found"}

        logger.info(f"Seed kernel: {seed_kernel}")
        logger.info("")

        # Simulate C0_NO_WORKER state
        state = "C0_NO_WORKER"
        stuck_cycles = 5
        current_config = {
            "backend": "d2h_ring_fi_send",
            "placement": "split_put_wait",
            "sync": "d2h_ring",
            "issuer": "multi_warp",
            "granularity": "per_expert_batch",
        }

        logger.info(f"Simulated state: {state}")
        logger.info(f"Stuck cycles: {stuck_cycles}")
        logger.info(f"Current config: {current_config}")
        logger.info("")

        # Step 1: Show state-to-dimension mapping
        dimension, reason = STATE_TO_DIMENSION[state]
        logger.info(f"State -> Dimension mapping:")
        logger.info(f"  {state} -> dimension='{dimension}'")
        logger.info(f"  Reason: {reason}")
        logger.info("")

        # Step 2: Show alternatives
        alternatives = self.design_space.get_alternatives(dimension, current_config[dimension])
        logger.info(f"Alternatives for '{dimension}' (current='{current_config[dimension]}'):")
        for alt in alternatives:
            info = self.design_space.get_value_info(dimension, alt)
            desc = info.get("description", "No description")
            if isinstance(desc, str):
                desc = " ".join(desc.strip().split())[:100]
            violations = self.design_space.check_constraints(current_config, dimension, alt)
            status = "VALID" if not violations else f"BLOCKED ({', '.join(violations)})"
            logger.info(f"  {alt}: {status}")
            logger.info(f"    {desc}")
        logger.info("")

        # Step 3: Run actual recovery (L0 only for demo)
        logger.info("Running recovery (L0 parse only for demo)...")
        logger.info("")

        report = self.run(
            state=state,
            stuck_cycles=stuck_cycles,
            current_config=current_config,
            seed_kernel=seed_kernel,
            dry_run=False,
        )

        # Pretty-print report
        logger.info("")
        logger.info("=" * 60)
        logger.info("RECOVERY REPORT")
        logger.info("=" * 60)
        logger.info(f"State: {report['state']}")
        logger.info(f"Dimension targeted: {report['dimension_targeted']}")
        logger.info(f"Candidates tried: {report['candidates_tried']}")
        logger.info("")

        for c in report.get("candidates", []):
            logger.info(f"  {c['alternative_value']}: "
                        f"level={c['eval_level']} "
                        f"passed={c['eval_passed']} "
                        f"score={c['eval_score']}")
            if c.get("eval_diagnostics"):
                logger.info(f"    diag: {c['eval_diagnostics'][:100]}")

        logger.info("")
        logger.info(f"Recommendation: {report.get('recommendation', 'N/A')}")

        return report


# =============================================================================
# CLI Argument Parsing
# =============================================================================

def parse_current_config(config_str: str) -> dict[str, str]:
    """
    Parse a current config string like 'B=x,P=y,S=z,I=w,G=v'
    into a dimension dict.
    """
    result = {}
    for part in config_str.split(","):
        part = part.strip()
        if "=" not in part:
            continue
        key, val = part.split("=", 1)
        key = key.strip()
        val = val.strip()
        # Map short symbols to full names
        dim_name = DIM_SYMBOL_MAP.get(key, key)
        result[dim_name] = val
    return result


def main():
    parser = argparse.ArgumentParser(
        description="Evolution-guided recovery for the Transport supervisor",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Investigate C0_NO_WORKER stuck state
  %(prog)s --state C0_NO_WORKER --stuck-cycles 5

  # Dry-run: show what would happen
  %(prog)s --state DISPATCHING --stuck-cycles 3 --dry-run

  # Full specification with custom config
  %(prog)s --state C0_TIMEOUT --stuck-cycles 7 \\
    --current-config 'B=d2h_ring_fi_send,P=split_put_wait,S=d2h_ring,I=multi_warp,G=per_expert_batch' \\
    --seed-kernel /path/to/transport_worker.cpp

  # Demo mode
  %(prog)s --demo

State-to-dimension mapping:
  C0_NO_WORKER        -> sync       (GPU signal not reaching CPU worker)
  C0_TIMEOUT          -> issuer     (GPU coordinator not generating descriptors)
  DISPATCHING         -> backend    (fi_writemsg posting but data not arriving)
  DISPATCHING_TIMEOUT -> backend    (transfer started but timing out)
  NO_WORKERS          -> (none)     (infrastructure issue)
  PEERS_MISSING       -> (none)     (infrastructure issue)
  ALL_PASS            -> (none)     (no recovery needed)
""",
    )

    parser.add_argument(
        "--state",
        type=str,
        help="Supervisor state (C0_NO_WORKER, C0_TIMEOUT, DISPATCHING, etc.)",
    )
    parser.add_argument(
        "--stuck-cycles",
        type=int,
        default=3,
        help="Number of consecutive cycles in this state (default: 3)",
    )
    parser.add_argument(
        "--current-config",
        type=str,
        default=None,
        help="Current CULink config: 'B=x,P=y,S=z,I=w,G=v'",
    )
    parser.add_argument(
        "--seed-kernel",
        type=str,
        default=None,
        help="Path to the seed kernel file (default: transport_worker.cpp)",
    )
    parser.add_argument(
        "--config",
        type=str,
        default=None,
        help=f"Path to recovery config YAML (default: {DEFAULT_CONFIG_PATH})",
    )
    parser.add_argument(
        "--design-space",
        type=str,
        default=None,
        help=f"Path to CULink-EFA design space YAML (default: {DEFAULT_DESIGN_SPACE})",
    )
    parser.add_argument(
        "--templates-dir",
        type=str,
        default=None,
        help=f"Path to recovery templates directory (default: {DEFAULT_TEMPLATES_DIR})",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would happen without generating/evaluating candidates",
    )
    parser.add_argument(
        "--demo",
        action="store_true",
        help="Run demo mode with mock C0_NO_WORKER state",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Output JSON report to stdout",
    )
    parser.add_argument(
        "--verbose",
        "-v",
        action="store_true",
        help="Enable verbose logging",
    )

    args = parser.parse_args()

    # Setup logging
    level = logging.DEBUG if args.verbose else logging.INFO
    logging.basicConfig(
        level=level,
        format="%(asctime)s [%(levelname)s] %(message)s",
        handlers=[logging.StreamHandler()],
    )

    # Validate arguments
    if not args.demo and not args.state:
        parser.error("--state is required (or use --demo)")

    # Initialize orchestrator
    orchestrator = RecoveryOrchestrator(
        config_path=args.config,
        design_space_path=args.design_space,
        templates_dir=args.templates_dir,
    )

    # Run
    if args.demo:
        report = orchestrator.run_demo()
    else:
        current_config = None
        if args.current_config:
            current_config = parse_current_config(args.current_config)

        report = orchestrator.run(
            state=args.state,
            stuck_cycles=args.stuck_cycles,
            current_config=current_config,
            seed_kernel=args.seed_kernel,
            dry_run=args.dry_run,
        )

    # Output
    if args.json:
        print(json.dumps(report, indent=2, default=str))

    return 0 if report.get("best_candidate") or report.get("dry_run") else 1


if __name__ == "__main__":
    sys.exit(main())
